apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applications
spec:
  generators:
    - git:
        repoURL: https://github.com/your-org/your-repo.git
        revision: HEAD
        directories:
          - path: apps/*/envs/dev
  template:
    metadata:
      name: '{{path.basename}}-dev'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/your-repo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-dev'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
