apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: file-event-source
  namespace: es
spec:
  file:
    example:
      eventType: file
      watchPathConfig:
        directory: "/path/to/mounted/files"
        pathRegexp: ".*\\.txt"
      polling: true
      pollingInterval: 30s
